from typing import Protocol
from .models import Task

class TaskRepositoryPort(Protocol):
    def save(self, task: Task) -> None: ...
    def get(self, task_id: str) -> Task: ...
    def list_by_user(self, user_id: str) -> list[Task]: ...
    def list_by_date(self, user_id: str, date: str) -> list[Task]: ...
    def complete(self, task_id: str) -> None: ...
    def delete(self, task_id: str) -> None: ...
