from typing import Protocol, Optional
from .models import Character, MBTIType

class CharacterRepositoryPort(Protocol):
    def get_all(self) -> list[Character]: ...
    def get(self, character_id: str) -> Optional[Character]: ...
    def get_by_mbti(self, mbti: MBTIType) -> Optional[Character]: ...
