from typing import Protocol, Optional
from datetime import date
from .models import ScreenTimeRecord, ScreenTimeAnalysisResult

class ScreenTimeRepositoryPort(Protocol):
    def save(self, record: ScreenTimeRecord) -> None: ...
    def get_by_date(self, user_id: str, target_date: date) -> Optional[ScreenTimeRecord]: ...
    def list_by_range(self, user_id: str, start_date: date, end_date: date) -> list[ScreenTimeRecord]: ...
    def list_recent(self, user_id: str, days: int = 7) -> list[ScreenTimeRecord]: ...

class ScreenTimeImageAnalyzerPort(Protocol):
    def analyze(self, image_bytes: bytes, mime_type: str = "image/png") -> ScreenTimeAnalysisResult: ...
