from typing import Protocol, Optional
from .models import User

class UserRepositoryPort(Protocol):
    def save(self, user: User) -> None: ...
    def get(self, user_id: str) -> Optional[User]: ...
    def update_selected_character(self, user_id: str, character_id: str) -> None: ...
